// ── Shared constants used across all pages ──────────────────────────────────

export const RETAIL_AGENTS = [
  'Accurate & Affordable Insurance Inc.',
  'Acrisure of California',
  'ACW Insurance',
  'Adlakha Plastic Surgery',
  'Agri-Center Insurance Agency Inc',
  'AHTKY Insurance Agency, LLC',
  'AIA Associate, Inc.',
  'Aihara & Associates Insurance Services, Inc.',
  'Aihara Financial Insurance Services, Inc.',
  'Alla Bezkrovny',
  'Alliance 360 Insurance Solutions',
  'Alliant Insurance Services',
  'Alliant Insurance Services, Inc.',
  "America's Choice Insurance Agency",
  'American Mutual Group',
  'American Risk Management',
  'Amity Insurance',
  'AMPA Insurance Agency, Inc.',
  'Anthony Insurance',
  'Armstrong Insurance Services',
  'Arrowood Insurance Services',
  'Arthur J Gallagher Risk Mgmt Svcs - IL',
  'Artur Momiyan Insurance Agency',
  'Associated Insurance & Financial Services, LLC',
  'Associated Insurance & Financial Services, LLC t/a',
  'Associated Pacific Insurance',
  'ASSOCIATED PACIFIC INSURANCE SERVICES',
  'Atlantic Insurance Services',
  'Atlas Insurance Agency',
  'Atlas Insurance Agency, Inc.',
  'Aura Risk Management',
  'Barclay Group',
  'Barnes Financial Group',
  'Bart J De Lio Insurance Agency',
  'Belen Sanchez Insurance Agency, Inc.',
  'Benchmark Financial Limited',
  'Bennett Gould & Partners',
  'Boardman Hamilton Co.',
  'Body & Borneman Assoc.',
  'Bone Robertson & McBride Inc.',
  'Bourdreau Insurance Services',
  'Brad Emmons Brokerage',
  'Brad Spurgeon Insurance Agency',
  'Broussard Insurance Services',
  'Brown & Brown Pacific Insurance Services, Inc.',
  'Bruce Cruickshank Insurance Services, Inc.',
  'Budd Agency Inc.',
  'Burnham Risk and Insurance Solutions, LLC',
  'Business Insurance Services',
  'C&R Insurance Services, Inc.',
  'C3 Risk & Insurance Services',
  'Cal Coast Insurance Agency',
  'Cal Overseas Insurance Service',
  'Cal-Kor Insurance',
  'California Horizon Insurance Services, Inc.',
  'California Plus Insurance Service',
  'California Security Insurance Services',
  'CAP Physicians Insurance Agency',
  'Chambers & Company Insurance Brokers',
  'Champion Insurance Agency',
  'Chelbay, Schular, Chelbay',
  'Christi Insurance',
  'CNA Direct Bill',
  'Colony West Financial Insurance Services, Inc.',
  'Commercial Management Insurance Services',
  'Comprehensive Insurance Underwriters',
  'Conners Insurance',
  'Core Insurance Group',
  'Correa Insurance Agency',
  'CRC Insurance Group',
  'CrossKeys Insurance Inc.',
  'Curtis Insurance Agency',
  'DARB Insurance',
  'Daiwa Insurance Marketing, Inc.',
  'Danone Simpson',
  'Daragon Insurance Services',
  'Darr Schackow Insurance Agency',
  'Dave Terpening Insurance Agency, Inc.',
  'David Jaskolski Insurance Agency Inc.',
  'Davis & Madden Insurance',
  'Dealer Cover Insurance Services',
  'DHW Insurance Brokers',
  'DIFCO Insurance',
  'Digital Insurance, LLC',
  'Dioji Inc.',
  'DMK Advisor Group, Inc.',
  'Dynamite Insurance Brokerage',
  'E2E Benefit Services',
  'Echo Insurance Services',
  'Edgewood Partners Insurance Center',
  'Egloff Insurance Agency',
  'Element Risk Management',
  'Emory P. Stephens Insurance Service, Inc.',
  'EPIC Insurance Brokers and Consultants',
  'Executive Compensation Plans',
  'Fairmont Insurance Brokers, Ltd.',
  'FIA Insurance Services, Inc.',
  'Fina Insurance Agency',
  'Finance Insurance',
  'Finestone Insurance Agency',
  'Flippa Inc.',
  'Foner Insurance Assoc.',
  'Foresight Benefits & Insurance Services',
  'Foroutan Insurance Services',
  'Foundation Risk Partners Corp.',
  'Fukuma Insurance Agency',
  'Gallant Risk & Insurance Services, Inc.',
  'Gentzler & Smith',
  'George Petersen Insurance Agency, Inc.',
  'Gerard Insurance Service',
  'Gladius Insurance Services LLC',
  'Glenn Insurance Inc.',
  'Gloria Kilmer Insurance',
  'GMG Insurance',
  'Golden Alliance Insurance Agency, Inc.',
  'Good News Insurance Agency',
  'Goretti Nobre Insurance Services',
  'Granados Insurance',
  'Great American Direct Bill',
  'Greyhawk Brothers LLC',
  'Grove Financial & Associates, Inc.',
  'Hanover Insurance Group',
  'Hatfield Group LLC',
  "Hawk's Bay Insurance Group Inc.",
  'HCP National Insurance Services, Inc.',
  'Hendricks-Hodgkiss Co., Inc.',
  'HUB International',
  'HUB International Insurance Services Inc.',
  'HUB Intl Insurance Services Inc. (Invensure)',
  'Hughes Insurance Services',
  'IGO Insurance Agency',
  'Independent Broker Network George Menasce',
  'Innovative Solutions Insurance Services',
  'Insurance Solutions Group of Troy, LLC',
  'Insureitman, LLC',
  'Integrated Insurance Agency Inc.',
  'Invensure Insurance Brokers, Inc.',
  'Jackson Insurance Services',
  'Jade Insurance LLC',
  'James Kelley Insurance Agency',
  'James P. Bennett & Company',
  'Jeff Williamson Insurance LLC',
  'John Colby Insurance Agency',
  'John H. Connors Insurance',
  'John L Raya Insurance Agency Inc.',
  'Jonas Insurance Services',
  'JTR & Associates',
  'J. Morey Aihara Insurance Services LLC',
  'Kalyan J',
  'Kamiya Insurance Agency',
  'Kappauf Insurance Agency',
  'KASH Insurance Agency',
  'Kenbanc Insurance Services',
  'Khadem Insurance Services',
  'KMRD Partners',
  'Koors Insurance and Financial Services',
  'Kramer-Warner Associates',
  'Kurt Wolff',
  'LaBarre/Oksnee Insurance Agency, LLC',
  'Laura Walleman Insurance Service',
  'Lawyers Pacific Insurance Brokerage, Inc.',
  'LBW Insurance and Financial Services',
  'LCJ Insurance Services, Inc.',
  'Leavitt Pacific Insurance Brokers, Inc.',
  'Lennon Insurance Agency LLC',
  'Liberty Axiom',
  'Liberty Browning Insurance Brokers',
  'Liberty Chicago',
  'Liberty Company Insurance Brokers, Inc.',
  'Liberty Cormarc Insurance Services',
  'Liberty Dale Group',
  'Liberty DEP',
  'Liberty Fort Lauderdale',
  'Liberty Home Port Insurance Group, Inc.',
  'Liberty Inland Empire',
  'Liberty Irvine',
  'Liberty Los Angeles',
  'Liberty Mascolino',
  'Liberty Mitchell & Mitchell Insurance Brokers',
  'Liberty Orange County Insurance Brokers',
  'Liberty Reno',
  'Liberty San Diego',
  'Liberty San Francisco Bay Area',
  'Liberty Santa Rosa',
  'Liberty Spicewood',
  'Liberty Valley',
  'Lighthouse Commercial Insurance',
  'Lindenwood Insurance Services',
  'Lockton Insurance Brokers, LLC',
  'Loomis Company',
  'Lutz Ventures Insurance',
  'Lynn Kiecke, Lackey',
  'Macolino Risk Management',
  'Mag Mutual Insurance Agency LLC',
  'Manan',
  'Manny Mamaghan Insurance, Inc.',
  'Mark Insurance Services',
  'Martinelli Benefits Advisors',
  'Marumoto Insurance Agency, LLC',
  'McDonald-Leavitt Insurance Agency',
  'McGee Group',
  'McGoldrick Insurance Agency',
  'McGrory Insurance Services Inc.',
  'McPhee & Associates, Inc.',
  'Meslee Insurance Services',
  'MHH Insurance Agency',
  'Michael Correa Insurance',
  'MIF Insurance Agency',
  'Mike McFarlin Insurance Agency, LLC',
  'Minato Insurance Agency, Inc.',
  'Mitch Feingersch Insurance Agency',
  'Miyazaki Insurance Services',
  'Monica Salmon Insurance Agency',
  'Montgomery Insurance',
  'Moreman Moore',
  'Morgan Benjamin Insurance',
  'Moriwaki, Imai & Fujita, Inc.',
  'Morris & Garritano Insurance Agency, Inc.',
  'MPL Brokers LLC',
  'Mutual Underwriters',
  'Nakazawa Insurance Services',
  'New England Risk Management, Inc.',
  'Nigel Green Insurance Agency Inc.',
  'NJ Persofsky & Associates',
  'Noguchi & Associates',
  'Northeast Risk Solutions Insurance & Bonding',
  "O'Brien Insurance",
  'Ogino-Aizumi Insurance Agency',
  'Ogishima & Associates',
  'Olivia Insurance',
  'One General Agency',
  'Overby Seawell Company',
  'Owens Insurance',
  'Pacific Excess Insurance Marketing, Inc.',
  'Passey-Bond Co., Inc.',
  'Patton Associates',
  'Perfect Circle Insurance Services',
  'Performance Health',
  'Phelan Insurance Agency',
  'Philadelphia Direct Bill',
  'Physicians Insurance Consultants',
  'PIM, LLC',
  'PMI Services',
  'Praxis Insurance Associates, LLC',
  'Prendiville Agency, Inc.',
  'Professional Resource Insurance Agency LLC',
  'Providence Risk Group',
  'Pyramid Insurance Centre, LTD',
  'Quality Insurance Services',
  'R.L. Milsner, Inc.',
  'Radin Insurance Agency',
  'Radosevic Insurance',
  'Ray Williamson Insurance Services',
  'Regent Insurance',
  'REI Physicians Insurance Solutions LLC',
  'Reilly Insurance',
  'Ricardo Oropeza',
  'Richard Freeman',
  'Riosca Insurance Services',
  'RM Echaveste Insurance Agency',
  'RMG Insurance',
  'Robert McIntyre Insurance, Inc.',
  'Roger Smith Insurance Agency',
  'Ron Ronner Insurance Agency',
  'Rossmore Property & Casualty Insurance Agency, Inc.',
  'Rotunno Insurance Agency',
  'Rovner Insurance Group',
  'Rubicon Insurance Services, LLC',
  'Russell E. Foster Insurance',
  'S&K Financial and Insurance Service, Inc.',
  'Saurer Insurance Agency',
  'Serpe Insurance Agency',
  'Shiva Mirzai Insurance Agency',
  'Socius Insurance Services Inc.',
  'Specialty Insurance',
  'Stern Risk Partners',
  'Strategic Insurance Services',
  'SullivanCurtisMonroe Insurance Services, LLC',
  'Symphony Risk Healthcare Insurance Services, LLC',
  'Symphony Risk Solutions LLC',
  'Tattersall Insurance',
  'Test ABC',
  'Test Agent',
  'Test for Update',
  'Texas Commercial Agency',
  'Texas Insurance Options, LLC',
  'The B.R.&Y. Insurance Agency, Inc.',
  'The Beacon Group',
  'The Brokerage Commercial Insurance Services, Inc.',
  'The Buren Insurance Group, Inc.',
  'The Empire Company',
  'The Family Insurance Store, Inc.',
  'The Hauser Group',
  'The Insurance Exchange LTD',
  'The J. Morey Company, Inc.',
  'The Liberty Company Insurance Brokers',
  'The Martin Company',
  'The Wooditch Company',
  'THINK Insurance',
  'TIB Transportation Insurance Brokers',
  'Tip Top Insurance Agency',
  'Todd Lizak',
  'Thomas McKee Insurance',
  'Trace Insurance Services',
  'Transform Insurance LLC',
  'Triangle Test INK',
  'Truex Insurance Agency',
  'UNIK Insurance Services',
  'United Agencies Burbank Insurance',
  'United Lines Insurance Brokers Inc.',
  'Universal Insurance Group',
  'USI Affinity',
  'USI Insurance Services',
  'USI Southwest, Inc.',
  'Van Beurden Insurance Services, Inc.',
  'Vantreo Insurance Brokerage',
  'Vartan Safarian Insurance',
  'Vivian Kim Insurance',
  'VP Custom Insurance Solutions Inc.',
  'Walter Mortensen Insurance / INSURICA',
  'Westtown Insurance',
  'William Go Insurance Agency',
  'Windfall Insurance Service',
  'Wizard Insurance Services',
  'Wood Gutmann & Bogart Insurance Brokers',
  'Yates Insurance Services',
]
