// Mock data – replace with real API calls once backend is live

export const mockStats = {
  users: 1248,
  agents: 342,
  clients: 8934,
  policies: 15672,
  usersChange: '+12%',
  agentsChange: '+5%',
  clientsChange: '+18%',
  policiesChange: '+23%',
}

export const mockPremiumData = [
  { month: "Jun 25", premium: 710000, written: 660000, billed: 620000 },
  { month: "Jul 25", premium: 680000, written: 620000, billed: 590000 },
  { month: "Aug 25", premium: 750000, written: 700000, billed: 670000 },
  { month: "Sep 25", premium: 820000, written: 760000, billed: 730000 },
  { month: "Oct 25", premium: 790000, written: 730000, billed: 700000 },
  { month: "Nov 25", premium: 870000, written: 810000, billed: 780000 },
  { month: "Dec 25", premium: 950000, written: 890000, billed: 860000 },
  { month: "Jan 26", premium: 1020000, written: 960000, billed: 920000 },
  { month: "Feb 26", premium: 980000, written: 910000, billed: 880000 },
  { month: "Mar 26", premium: 1100000, written: 1040000, billed: 1000000 },
  { month: "Apr 26", premium: 1060000, written: 990000, billed: 950000 },
  { month: "May 26", premium: 1140000, written: 1070000, billed: 1030000 },
]

export const mockAppStats = [
  { name: 'Approved', value: 45, color: '#10b981' },
  { name: 'Pending', value: 28, color: '#f59e0b' },
  { name: 'In Review', value: 17, color: '#06b6d4' },
  { name: 'Declined', value: 10, color: '#ef4444' },
]

export const mockPolicies = [
  {
    id: 1,
    policyNumber: 'BME1-A7116793-TIL-25 (7702)',
    name: 'KING CHEESE CORPORATION',
    effectiveDate: '01/02/2025',
    expirationDate: '01/02/2026',
    status: 'Active',
    transactionStatus: 'New Business',
    lastModifiedBy: 'Nish Patel',
    annualPremium: 16496.42,
    writtenPremium: 15988,
    billedPremium: 15988,
    annualPremiumStr: '$16,496.42',
    writtenPremiumStr: '$15,988.00',
    billedPremiumStr: '$15,988.00',
    assignedTo: 'Nish Patel',
    lob: 'Boiler & Machinery',
    policyState: 'California',
    policyType: 'Monoline',
    division: 'Arrowood Insurance Services, Inc.',
    branch: 'Liberty Arrowood Insurance Services, GP',
    retailAgent: 'Manan',
    retailAgentContactName: 'Manan M Makhija',
    retailAgentContactEmail: 'manan@gmail.com',
    billingType: '-- Select --',
    auraBrokerName: 'test',
    auraBrokerEmail: 'tst@test.com',
    issuingCarrier: 'Travelers Property Casualty Company Of America',
    billingCarrier: 'Travelers Companies, Inc.',
    clientType: 'Company/Organization',
    typeOfBusiness: 'Corporation',
    natureOfBusiness: 'Cheese Manufacturing',
    establishmentDate: '08/2023',
    yearsInBusiness: '2',
    address1: '229 RAILROAD AVE',
    address2: '',
    zip: '91016',
    county: 'Los Angeles',
    city: 'Monrovia',
  },
  {
    id: 2,
    policyNumber: 'OAK00098526 (7699)',
    name: 'Oak Park Townhomes - 1373 Oakmont St',
    effectiveDate: '05/01/2026',
    expirationDate: '12/15/2026',
    status: 'Quote',
    transactionStatus: 'Quote',
    lastModifiedBy: 'Nish Patel',
    annualPremium: 20859.23,
    writtenPremium: 14293.13,
    billedPremium: 14293.13,
    annualPremiumStr: '$20,859.23',
    writtenPremiumStr: '$14,293.13',
    billedPremiumStr: '$14,293.13',
    assignedTo: 'Nish Patel',
    lob: 'Commercial Property',
    policyState: 'Kansas',
    policyType: 'Monoline',
    division: 'SpiceWood',
    branch: 'AL/TN/MO/KS McDermott',
    retailAgent: 'Texas Commercial Agency',
    retailAgentContactName: 'Michelle Moulton',
    retailAgentContactEmail: 'michelle.moulton@libertycompany.com',
    billingType: 'Agency Billing',
    auraBrokerName: 'Michelle Moulton',
    auraBrokerEmail: 'michelle.moulton@libertycompany.com',
    issuingCarrier: 'Landmark American Ins Co',
    billingCarrier: 'RT Specialty Insurance Services',
    clientType: 'Company/Organization',
    typeOfBusiness: '',
    natureOfBusiness: '',
    address1: '1373 Oakmont St',
    address2: '',
    zip: '67460',
    county: 'Mcpherson',
    city: 'Mcpherson',
  },
  {
    id: 3,
    policyNumber: 'FLY-CB-AF9RS4KVZ-005 (7697)',
    name: 'Hamed Javadi DDS MS, Inc',
    effectiveDate: '01/05/2026',
    expirationDate: '01/05/2027',
    status: 'Active',
    transactionStatus: 'Renewal',
    lastModifiedBy: 'Aman Tiwari',
    annualPremium: 3998,
    writtenPremium: 3998,
    billedPremium: 3998,
    annualPremiumStr: '$3,998.00',
    writtenPremiumStr: '$3,998.00',
    billedPremiumStr: '$3,998.00',
    assignedTo: 'Aman Tiwari',
    lob: 'Cyber/Network Liability',
    policyState: 'California',
    policyType: 'Monoline',
    division: 'Aura Risk Management & Insurance Services, LLC',
    branch: 'Aura Risk Management & Insurance Services, LLC',
    retailAgent: 'Liberty Los Angeles',
    retailAgentContactName: 'Bill Holden',
    retailAgentContactEmail: 'bholden@libertycompany.com',
    billingType: 'Agency Billing',
    auraBrokerName: 'test',
    auraBrokerEmail: 'tst@test.com',
    issuingCarrier: 'Spinnaker Insurance Company, a stock company',
    billingCarrier: 'Sayata US Insurance Services, Inc',
    clientType: 'Company/Organization',
    typeOfBusiness: 'Corporation',
    natureOfBusiness: '',
    address1: '666 3rd St',
    address2: 'Ste 280',
    zip: '94901',
    county: 'Marin',
    city: 'San Rafael',
  },
  {
    id: 4,
    policyNumber: 'WDBB-SATIN-10026-00 (7642)',
    name: 'Golden Gate Holdings of Lockhart LLC',
    effectiveDate: '05/01/2026',
    expirationDate: '05/01/2027',
    status: 'Active',
    transactionStatus: 'New Business',
    lastModifiedBy: 'Nish Patel',
    annualPremium: 11839.46,
    writtenPremium: 11839.46,
    billedPremium: 11839.46,
    annualPremiumStr: '$11,839.46',
    writtenPremiumStr: '$11,839.46',
    billedPremiumStr: '$11,839.46',
    assignedTo: 'Nish Patel',
    lob: 'Commercial - Windstorm Deductible Buy Back',
    policyState: 'Texas',
    policyType: 'Monoline',
    division: 'Aura Risk Management & Insurance Services, LLC',
    branch: 'Aura Risk Management & Insurance Services, LLC',
    retailAgent: 'Liberty Spicewood',
    retailAgentContactName: 'Tiffany Howard',
    retailAgentContactEmail: 'tiffany.howard@libertycompany.com',
    billingType: 'Agency Billing',
    auraBrokerName: 'Urvish Patel',
    auraBrokerEmail: 'upatel@aurarisk.com',
    issuingCarrier: 'Satinwood Underwriting Limited',
    billingCarrier: 'Ballantyne Brokers Ltd',
    clientType: 'Company/Organization',
    typeOfBusiness: 'Limited Liability Corporation (LLC)',
    natureOfBusiness: 'Habitational',
    establishmentDate: '04/2016',
    yearsInBusiness: '10',
    address1: '728 W San Antonio St',
    address2: '',
    zip: '78644',
    county: 'Caldwell',
    city: 'Lockhart',
  },
  {
    id: 5,
    policyNumber: 'VAVEHO-26-10453 (7621)',
    name: 'd test',
    effectiveDate: '05/06/2026',
    expirationDate: '05/06/2027',
    status: 'Active',
    transactionStatus: 'New Business',
    lastModifiedBy: 'Nish Patel',
    annualPremium: 1508.77,
    writtenPremium: 1508.77,
    billedPremium: 1508.77,
    annualPremiumStr: '$1,508.77',
    writtenPremiumStr: '$1,508.77',
    billedPremiumStr: '$1,508.77',
    assignedTo: 'Nish Patel',
    lob: 'Home Owners',
    policyState: 'Florida',
    policyType: 'Monoline',
    division: 'Aura Risk Management & Insurance Services, LLC',
    branch: 'Aura Risk Management & Insurance Services, LLC',
    retailAgent: 'A',
    retailAgentContactName: 'a a',
    retailAgentContactEmail: 'd@d.com',
    billingType: 'Agency Billing',
    auraBrokerName: 'd',
    auraBrokerEmail: 'd@d.com',
    issuingCarrier: 'Vave Home Owner',
    billingCarrier: 'Ballantyne Brokers Ltd',
    clientType: 'Person/Individual',
    firstName: 'd',
    middleName: '',
    lastName: 'test',
    licenseNo: '',
    designation: '-- Designation --',
    address1: '30 baker st',
    address2: '',
    zip: '14580',
    county: 'Monroe',
    city: 'Webster',
  },
  {
    id: 6,
    policyNumber: 'P Q000004934 (7605)',
    name: 'JJJ95TEST SILVA',
    effectiveDate: '15-04-2026',
    expirationDate: '15-04-2027',
    status: 'Active',
    transactionStatus: 'New Business Reinstatement',
    lastModifiedBy: 'Nish Patel',
    annualPremium: 5159,
    writtenPremium: 5009,
    billedPremium: 5009,
    annualPremiumStr: '$5,159.00',
    writtenPremiumStr: '$5,009.00',
    billedPremiumStr: '$5,009.00',
    assignedTo: 'Nish Patel',
    lob: 'Business Auto',
    policyState: 'California',
    policyType: 'Monoline',
    division: 'Aura Risk Management & Insurance Services, LLC',
    branch: 'Aura Risk Management & Insurance Services, LLC',
    retailAgent: '*Galligan & Associates',
    retailAgentContactName: 'agent',
    retailAgentContactEmail: 'agent@gmail.com',
    billingType: 'Agency Billing',
    auraBrokerName: 'AuraBroker',
    auraBrokerEmail: 'AuraBroker@gmail.com',
    issuingCarrier: 'Accredited Specialty Insurance Company (Sayata)',
    billingCarrier: 'Sayata US Insurance Services, Inc',
    clientType: 'Company/Organization',
    typeOfBusiness: 'Corporation',
    natureOfBusiness: '',
    address1: '953 Dexter St',
    address2: '',
    zip: '90042',
    county: 'Los Angeles',
    city: 'Los Angeles',
  },
  {
    id: 7,
    policyNumber: 'POL-2024-001240',
    name: 'Coastal Wind Energy Inc.',
    effectiveDate: '05/15/2024',
    expirationDate: '05/15/2025',
    status: 'Pending',
    transactionStatus: 'Submitted',
    lastModifiedBy: 'M. Foster',
    annualPremium: 320000,
    writtenPremium: 0,
    billedPremium: 0,
    annualPremiumStr: '$320,000.00',
    writtenPremiumStr: '$0.00',
    billedPremiumStr: '$0.00',
    assignedTo: 'M. Foster',
    lob: 'Commercial Property',
    policyState: 'Texas',
    policyType: 'Monoline',
    division: 'Aura Risk Management & Insurance Services, LLC',
    branch: 'Aura Risk Management & Insurance Services, LLC',
    retailAgent: 'Liberty Spicewood',
    retailAgentContactName: 'Agent Name',
    retailAgentContactEmail: 'agent@email.com',
    billingType: 'Agency Billing',
    auraBrokerName: 'M. Foster',
    auraBrokerEmail: 'mfoster@aurarisk.com',
    issuingCarrier: 'Travelers Property Casualty',
    billingCarrier: 'Travelers Companies, Inc.',
    clientType: 'Company/Organization',
    typeOfBusiness: 'Corporation',
    natureOfBusiness: 'Energy',
    address1: '1 Wind Farm Rd',
    address2: '',
    zip: '77001',
    county: 'Harris',
    city: 'Houston',
  },
  {
    id: 8,
    policyNumber: 'POL-2024-001241',
    name: 'Pioneer Farming Co-Op',
    effectiveDate: '06/01/2023',
    expirationDate: '06/01/2024',
    status: 'Cancelled',
    transactionStatus: 'Cancelled',
    lastModifiedBy: 'T. Brooks',
    annualPremium: 18500,
    writtenPremium: 9000,
    billedPremium: 8500,
    annualPremiumStr: '$18,500.00',
    writtenPremiumStr: '$9,000.00',
    billedPremiumStr: '$8,500.00',
    assignedTo: 'T. Brooks',
    lob: 'Boiler & Machinery',
    policyState: 'Iowa',
    policyType: 'Monoline',
    division: 'Arrowood Insurance Services, Inc.',
    branch: 'Liberty Arrowood Insurance Services, GP',
    retailAgent: 'Manan',
    retailAgentContactName: 'Manan M Makhija',
    retailAgentContactEmail: 'manan@gmail.com',
    billingType: 'Agency Billing',
    auraBrokerName: 'T. Brooks',
    auraBrokerEmail: 'tbrooks@aurarisk.com',
    issuingCarrier: 'Travelers Property Casualty Company Of America',
    billingCarrier: 'Travelers Companies, Inc.',
    clientType: 'Company/Organization',
    typeOfBusiness: 'Corporation',
    natureOfBusiness: 'Agriculture',
    address1: '500 Farm Road',
    address2: '',
    zip: '50010',
    county: 'Story',
    city: 'Ames',
  },
]

export const mockAgents = [
  { id: 1, name: 'James Martinez', code: 'AGT-001', email: 'j.martinez@insure.com', state: 'TX', status: 'Active', policies: 142, commission: '12%' },
  { id: 2, name: 'Sarah Thompson', code: 'AGT-002', email: 's.thompson@insure.com', state: 'CA', status: 'Active', policies: 98, commission: '10%' },
  { id: 3, name: 'Andrew Williams', code: 'AGT-003', email: 'a.williams@insure.com', state: 'FL', status: 'Inactive', policies: 45, commission: '8%' },
  { id: 4, name: 'Rita Chen', code: 'AGT-004', email: 'r.chen@insure.com', state: 'NY', status: 'Active', policies: 210, commission: '14%' },
  { id: 5, name: 'Kevin Patel', code: 'AGT-005', email: 'k.patel@insure.com', state: 'IL', status: 'Active', policies: 77, commission: '11%' },
]

export const mockCarriers = [
  { id: 1, name: 'Nationwide Insurance', code: 'NW', state: 'OH', status: 'Active', type: 'P&C', amBest: 'A+' },
  { id: 2, name: 'Liberty Mutual', code: 'LM', state: 'MA', status: 'Active', type: 'P&C', amBest: 'A' },
  { id: 3, name: 'Allstate Corporation', code: 'ALT', state: 'IL', status: 'Active', type: 'P&C', amBest: 'A+' },
  { id: 4, name: 'Travelers Group', code: 'TRV', state: 'CT', status: 'Active', type: 'P&C', amBest: 'A++' },
  { id: 5, name: 'Hartford Financial', code: 'HIG', state: 'CT', status: 'Inactive', type: 'P&C', amBest: 'A+' },
]

export const mockClients = [
  { id: 1, name: 'Riverside Corp Holdings', contact: 'David Kim', email: 'dkim@riverside.com', phone: '(512) 555-0142', city: 'Austin', state: 'TX', policies: 4, status: 'Active' },
  { id: 2, name: 'Oakwood Manufacturing LLC', contact: 'Lisa Park', email: 'lpark@oakwood.com', phone: '(213) 555-0278', city: 'Los Angeles', state: 'CA', policies: 2, status: 'Active' },
  { id: 3, name: 'Sunrise Properties Group', contact: 'Tom Reyes', email: 'treyes@sunrise.com', phone: '(305) 555-0391', city: 'Miami', state: 'FL', policies: 7, status: 'Active' },
  { id: 4, name: 'Blue Harbor Logistics', contact: 'Amy Johnson', email: 'ajohnson@blueharbor.com', phone: '(718) 555-0462', city: 'New York', state: 'NY', policies: 1, status: 'Pending' },
  { id: 5, name: 'Meridian Health Services', contact: 'Chris Nguyen', email: 'cnguyen@meridian.com', phone: '(312) 555-0587', city: 'Chicago', state: 'IL', policies: 3, status: 'Active' },
]

export const mockUsers = [
  { id: 1, name: 'Admin User', email: 'admin@insureproadmin.com', role: 'Super Admin', status: 'Active', lastLogin: '2024-03-15 09:30' },
  { id: 2, name: 'James Martinez', email: 'j.martinez@insure.com', role: 'Agent', status: 'Active', lastLogin: '2024-03-15 08:15' },
  { id: 3, name: 'Sarah Thompson', email: 's.thompson@insure.com', role: 'Agent', status: 'Active', lastLogin: '2024-03-14 16:45' },
  { id: 4, name: 'Mike Foster', email: 'm.foster@insure.com', role: 'Manager', status: 'Active', lastLogin: '2024-03-15 10:00' },
  { id: 5, name: 'Old Account', email: 'old@insure.com', role: 'Viewer', status: 'Inactive', lastLogin: '2024-01-01 12:00' },
]

export const mockActivities = [
  { id: 1, action: 'Policy Issued', detail: 'POL-2024-001238 – Meridian Health Services', user: 'K. Patel', time: '2 min ago', type: 'success' },
  { id: 2, action: 'Quote Created', detail: 'Blue Harbor Logistics – Workers Comp', user: 'R. Chen', time: '18 min ago', type: 'info' },
  { id: 3, action: 'Policy Expired', detail: 'POL-2024-001236 – Sunrise Properties Group', user: 'System', time: '1 hr ago', type: 'warning' },
  { id: 4, action: 'Renewal Processed', detail: 'POL-2024-001235 – Oakwood Manufacturing', user: 'S. Thompson', time: '3 hr ago', type: 'success' },
  { id: 5, action: 'Policy Cancelled', detail: 'POL-2024-001241 – Pioneer Farming Co-Op', user: 'T. Brooks', time: '5 hr ago', type: 'error' },
]
